### ISSUE TITLE
Heads Up: Changes in how Netbox Docker serves HTTP

### ISSUE THREAD

**Issue by cimnine** [CENGN/netbox-kubernetes#3]
I would like to inform you that we will change how Netbox Docker server HTTP traffic in the next version.
Instead of nginx serving static content and forwarding all dynamic content to gunicorn, we'll be using Nginx Unit to do both.

This means one less container and should overall simplify the deployment.

Please see https://github.com/netbox-community/netbox-docker/pull/361 for reference.

**Comment by mohahmed13** [comment]
Thanks for the heads up @cimnine! That's gonna simplify things significantly. 

Will keep an eye on upstream and we'll adapt our manifests accordingly.
